identifier-prefix: ogc.sosa.
name: Observations (ISO 19156, OGC/W3C SOSA)
abstract: Building blocks for implementation of OGC Observations Measurements and Samples (ISO 19156 aka OMS) using the OGC API Features schema and the OGC/W3C SOSA ontology
description: "Each building block defines a reusable JSON schema that is mapped to the equivalent SOSA concept (and transitively mapped to OMS requirements via SOSA).\n\nEach fragment allows for transparent and validatable use of JSON-LD contexts to map schema elements to equivalent terms from the SOSA ontology. \n\n _These components are under review by the OMS SWG as candidate canonical implementations._ \n\n Each building block allows for examples transformed to RDF, which in turn allows for the use of SHACL rules to enforce the semantics of the SOSA and OMS specifications.\n"
schema-mapping:
  default: https://opengeospatial.github.io/bblocks/annotated-schemas/
imports:
  - default
sparql:
  push: https://defs-dev.opengis.net/fuseki/data
  query: https://defs-dev.opengis.net/fuseki/query
